In [3]:
from sklearn.impute import SimpleImputer

In [2]:
imputer = SimpleImputer()

In [4]:
from sklearn.datasets import load_wine

In [8]:
wine = load_wine()

In [7]:
import pandas as pd
import numpy as np

In [16]:
wine.get("data")  # None
wine.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [18]:
X = pd.DataFrame(wine.get("data"), columns=wine.get('feature_names'))

In [19]:
X

     alcohol  malic_acid   ash  alcalinity_of_ash  ...  color_intensity   hue  od280/od315_of_diluted_wines  proline
0      14.23        1.71  2.43               15.6  ...             5.64  1.04                          3.92   1065.0
1      13.20        1.78  2.14               11.2  ...             4.38  1.05                          3.40   1050.0
2      13.16        2.36  2.67               18.6  ...             5.68  1.03                          3.17   1185.0
3      14.37        1.95  2.50               16.8  ...             7.80  0.86                          3.45   1480.0
4      13.24        2.59  2.87               21.0  ...             4.32  1.04                          2.93    735.0
..       ...         ...   ...                ...  ...              ...   ...                           ...      ...
173    13.71        5.65  2.45               20.5  ...             7.70  0.64                          1.74    740.0
174    13.40        3.91  2.48               23.0  ...             7.30  0.70                          1.56    750.0
175    13.27        4.28  2.26               20.0  ...            10.20  0.59                          1.56    835.0
176    13.17        2.59  2.37               20.0  ...             9.30  0.60                          1.62    840.0
177    14.13        4.10  2.74               24.5  ...             9.20  0.61                          1.60    560.0

[178 rows x 13 columns]

In [24]:
y = pd.DataFrame(wine.get("target"), columns=['class'])

In [29]:
y

     class
0        0
1        0
2        0
3        0
4        0
..     ...
173      2
174      2
175      2
176      2
177      2

[178 rows x 1 columns]

In [26]:
wine.get("target").shape, wine.get('target_names')

((178,), array(['class_0', 'class_1', 'class_2'], dtype='<U7'))

In [35]:
y = y['class'].map({0: 'class_0', 1: 'class_1', 2: 'class_2'})

In [36]:
y

0      class_0
1      class_0
2      class_0
3      class_0
4      class_0
        ...
173    class_2
174    class_2
175    class_2
176    class_2
177    class_2
Name: class, Length: 178, dtype: str

In [40]:
df = pd.concat((X,  y), axis=1)

In [42]:
df.to_csv('../../data/wine.csv', index=False)

In [43]:
df

     alcohol  malic_acid   ash  alcalinity_of_ash  ...   hue  od280/od315_of_diluted_wines  proline    class
0      14.23        1.71  2.43               15.6  ...  1.04                          3.92   1065.0  class_0
1      13.20        1.78  2.14               11.2  ...  1.05                          3.40   1050.0  class_0
2      13.16        2.36  2.67               18.6  ...  1.03                          3.17   1185.0  class_0
3      14.37        1.95  2.50               16.8  ...  0.86                          3.45   1480.0  class_0
4      13.24        2.59  2.87               21.0  ...  1.04                          2.93    735.0  class_0
..       ...         ...   ...                ...  ...   ...                           ...      ...      ...
173    13.71        5.65  2.45               20.5  ...  0.64                          1.74    740.0  class_2
174    13.40        3.91  2.48               23.0  ...  0.70                          1.56    750.0  class_2
175    13.27        4.28  2.26               20.0  ...  0.59                          1.56    835.0  class_2
176    13.17        2.59  2.37               20.0  ...  0.60                          1.62    840.0  class_2
177    14.13        4.10  2.74               24.5  ...  0.61                          1.60    560.0  class_2

[178 rows x 14 columns]

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
 13  class                         178 non-null    str
dtypes: float64(13), str(1)
memory usage: 20.8 KB

In [48]:
len(df), df.shape[0]

(178, 178)

In [49]:
df = df.sample(len(df))

In [51]:
df = df.reset_index(drop=True)

In [52]:
df

     alcohol  malic_acid   ash  alcalinity_of_ash  ...   hue  od280/od315_of_diluted_wines  proline    class
0      13.78        2.76  2.30               22.0  ...  0.70                          1.68    615.0  class_2
1      13.41        3.84  2.12               18.8  ...  0.91                          3.00   1035.0  class_0
2      11.56        2.05  3.23               28.5  ...  0.93                          3.69    465.0  class_1
3      11.84        2.89  2.23               18.0  ...  0.96                          2.52    500.0  class_1
4      12.72        1.81  2.20               18.8  ...  1.16                          3.14    714.0  class_1
..       ...         ...   ...                ...  ...   ...                           ...      ...      ...
173    13.76        1.53  2.70               19.5  ...  1.25                          3.00   1235.0  class_0
174    14.02        1.68  2.21               16.0  ...  1.04                          3.59   1035.0  class_0
175    12.51        1.24  2.25               17.5  ...  0.75                          1.51    650.0  class_2
176    12.42        2.55  2.27               22.0  ...  0.86                          3.30    315.0  class_1
177    13.48        1.81  2.41               20.5  ...  1.04                          3.47    920.0  class_0

[178 rows x 14 columns]

In [53]:
len(df)/100*80

142.4

In [55]:
df[:142], df[142:]

(     alcohol  malic_acid   ash  alcalinity_of_ash  ...    hue  od280/od315_of_diluted_wines  proline    class
 0      13.78        2.76  2.30               22.0  ...  0.700                          1.68    615.0  class_2
 1      13.41        3.84  2.12               18.8  ...  0.910                          3.00   1035.0  class_0
 2      11.56        2.05  3.23               28.5  ...  0.930                          3.69    465.0  class_1
 3      11.84        2.89  2.23               18.0  ...  0.960                          2.52    500.0  class_1
 4      12.72        1.81  2.20               18.8  ...  1.160                          3.14    714.0  class_1
 ..       ...         ...   ...                ...  ...    ...                           ...      ...      ...
 137    12.82        3.37  2.30               19.5  ...  0.720                          1.75    685.0  class_2
 138    12.29        1.61  2.21               20.4  ...  0.906                          1.82    870.0  class_1
 139    13.62        4.95  2.35               20.0  ...  0.910                          2.05    550.0  class_2
 140    14.75        1.73  2.39               11.4  ...  1.250                          2.73   1150.0  class_0
 141    11.45        2.40  2.42               20.0  ...  0.800                          3.39    625.0  class_1

 [142 rows x 14 columns],
      alcohol  malic_acid   ash  alcalinity_of_ash  ...   hue  od280/od315_of_diluted_wines  proline    class
 142    13.82        1.75  2.42               14.0  ...  1.01                          3.26   1190.0  class_0
 143    14.13        4.10  2.74               24.5  ...  0.61                          1.60    560.0  class_2
 144    12.53        5.51  2.64               25.0  ...  0.82                          1.69    515.0  class_2
 145    13.49        1.66  2.24               24.0  ...  0.98                          2.78    472.0  class_1
 146    13.05        2.05  3.22               25.0  ...  1.13                          3.20    830.0  class_0
 147    12.86        1.35  2.32               18.0  ...  0.76                          1.29    630.0  class_2
 148    14.39        1.87  2.45               14.6  ...  1.02                          3.58   1290.0  class_0
 149    12.16        1.61  2.31               22.8  ...  1.33                          2.26    495.0  class_1
 150    12.08        1.39  2.50               22.5  ...  0.93                          3.19    385.0  class_1
 151    12.34        2.45  2.46               21.0  ...  0.80                          3.38    438.0  class_1
 152    12.04        4.30  2.38               22.0  ...  0.79                          2.57    580.0  class_1
 153    12.29        2.83  2.22               18.0  ...  1.15                          3.30    290.0  class_1
 154    13.71        5.65  2.45               20.5  ...  0.64                          1.74    740.0  class_2
 155    13.48        1.67  2.64               22.5  ...  0.57                          1.78    620.0  class_2
 156    13.73        4.36  2.26               22.5  ...  0.78                          1.75    520.0  class_2
 157    14.22        3.99  2.51               13.2  ...  0.89                          3.53    760.0  class_0
 158    12.21        1.19  1.75               16.8  ...  1.28                          3.07    718.0  class_1
 159    13.64        3.10  2.56               15.2  ...  0.96                          3.36    845.0  class_0
 160    12.85        1.60  2.52               17.8  ...  1.09                          3.63   1015.0  class_0
 161    13.58        2.58  2.69               24.5  ...  0.74                          1.80    750.0  class_2
 162    11.62        1.99  2.28               18.0  ...  1.16                          2.96    345.0  class_1
 163    12.69        1.53  2.26               20.7  ...  0.96                          2.06    495.0  class_1
 164    13.58        1.66  2.36               19.1  ...  1.09                          2.88   1515.0  class_0
 165    11.66        1.88  1.92               16.0  ...  1.23                          2.14    428.0  class_1
 166    12.00        3.43  2.00               19.0  ...  0.93                          3.05    564.0  class_1
 167    13.51        1.80  2.65               19.0  ...  1.10                          2.87   1095.0  class_0
 168    13.83        1.65  2.60               17.2  ...  1.24                          3.37   1265.0  class_0
 169    13.05        1.77  2.10               17.0  ...  0.88                          3.35    885.0  class_0
 170    13.23        3.30  2.28               18.5  ...  0.56                          1.51    675.0  class_2
 171    13.56        1.73  2.46               20.5  ...  0.98                          3.03   1120.0  class_0
 172    12.93        2.81  2.70               21.0  ...  0.77                          2.31    600.0  class_2
 173    13.76        1.53  2.70               19.5  ...  1.25                          3.00   1235.0  class_0
 174    14.02        1.68  2.21               16.0  ...  1.04                          3.59   1035.0  class_0
 175    12.51        1.24  2.25               17.5  ...  0.75                          1.51    650.0  class_2
 176    12.42        2.55  2.27               22.0  ...  0.86                          3.30    315.0  class_1
 177    13.48        1.81  2.41               20.5  ...  1.04                          3.47    920.0  class_0

 [36 rows x 14 columns])