In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, LabelEncoder

In [4]:
df = pd.read_csv("../../data/job_salary_prediction_dataset.csv")

In [5]:
df

                 job_title  experience_years education_level  ...  remote_work certifications  salary
0              AI Engineer                10        Bachelor  ...       Hybrid              2  109413
1             Data Analyst                 5        Bachelor  ...           No              0   93764
2       Frontend Developer                18             PhD  ...           No              1  148123
3         Business Analyst                19             PhD  ...          Yes              0  189123
4          Product Manager                15        Bachelor  ...          Yes              0  165069
...                    ...               ...             ...  ...          ...            ...     ...
249995   Software Engineer                17             PhD  ...           No              1  127791
249996  Frontend Developer                20             PhD  ...           No              2  154593
249997    Business Analyst                 1        Bachelor  ...          Yes              0   75988
249998      Data Scientist                 0     High School  ...       Hybrid              5   90467
249999        Data Analyst                16         Diploma  ...           No              5  133084

[250000 rows x 10 columns]

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  str
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  str
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  str
 5   company_size      250000 non-null  str
 6   location          250000 non-null  str
 7   remote_work       250000 non-null  str
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), str(6)
memory usage: 30.7 MB

In [7]:
# Train test split

X = df.drop('salary', axis=1) # keep independent columns/ Features
y = df['salary'] # dependent

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [9]:
X_train.shape, X_test.shape

((175000, 9), (75000, 9))

In [10]:
X_test

                        job_title  experience_years education_level  ...     location remote_work certifications
38683                 AI Engineer                11        Bachelor  ...       Canada      Hybrid              3
64939             DevOps Engineer                 7          Master  ...        India      Hybrid              1
3954           Frontend Developer                10        Bachelor  ...        India         Yes              5
120374                AI Engineer                 8        Bachelor  ...      Germany          No              4
172861          Software Engineer                 2         Diploma  ...    Singapore      Hybrid              4
...                           ...               ...             ...  ...          ...         ...            ...
246904               Data Analyst                 4     High School  ...           UK      Hybrid              5
213577               Data Analyst                 4             PhD  ...  Netherlands         Yes              3
175132      Cybersecurity Analyst                19     High School  ...      Germany      Hybrid              2
75216   Machine Learning Engineer                11     High School  ...       Canada      Hybrid              5
145446            Product Manager                10        Bachelor  ...  Netherlands      Hybrid              3

[75000 rows x 9 columns]

In [11]:
df['remote_work'].unique()

<ArrowStringArray>
['Hybrid', 'No', 'Yes']
Length: 3, dtype: str

In [29]:
# OneHotEncoder nominal data 

ohe = OneHotEncoder( sparse_output=False, drop='first')
ohe.fit_transform(X_train[['remote_work', 'location']])

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(175000, 11))

In [30]:
ohe.categories_

[array(['Hybrid', 'No', 'Yes'], dtype=object),
 array(['Australia', 'Canada', 'Germany', 'India', 'Netherlands', 'Remote',
        'Singapore', 'Sweden', 'UK', 'USA'], dtype=object)]

In [31]:
ohe.transform(X_test[['remote_work', 'location']])

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(75000, 11))

In [32]:
ohe.get_feature_names_out()

array(['remote_work_No', 'remote_work_Yes', 'location_Canada',
       'location_Germany', 'location_India', 'location_Netherlands',
       'location_Remote', 'location_Singapore', 'location_Sweden',
       'location_UK', 'location_USA'], dtype=object)

In [33]:
ohe.feature_names_in_

array(['remote_work', 'location'], dtype=object)

In [34]:
ohe.inverse_transform(ohe.transform(X_test[['remote_work', 'location']]))

array([['Hybrid', 'Canada'],
       ['Hybrid', 'India'],
       ['Yes', 'India'],
       ...,
       ['Hybrid', 'Germany'],
       ['Hybrid', 'Canada'],
       ['Hybrid', 'Netherlands']], shape=(75000, 2), dtype=object)

In [35]:
# OrdinalEncoder Ordinal Data 
df['company_size'].unique()

<ArrowStringArray>
['Medium', 'Small', 'Large', 'Enterprise', 'Startup']
Length: 5, dtype: str

In [67]:
encoder = OrdinalEncoder(categories=[['Startup', 'Small', 'Medium', 'Large', 'Enterprise']])
encoder.fit_transform(X_train[['company_size']])

array([[0.],
       [1.],
       [0.],
       ...,
       [3.],
       [2.],
       [1.]], shape=(175000, 1))

In [68]:
encoder.categories_[0]

array(['Startup', 'Small', 'Medium', 'Large', 'Enterprise'], dtype=object)

In [69]:
arr[-1::-1]

array(['Startup', 'Small', 'Medium', 'Large', 'Enterprise'], dtype=object)

In [70]:
arr

array(['Enterprise', 'Large', 'Medium', 'Small', 'Startup'], dtype=object)

In [71]:
arr[-1]

'Startup'

In [72]:
-1 +  - 1

-2

In [75]:
encoder.inverse_transform([[1], [0], [4]])

array([['Small'],
       ['Startup'],
       ['Enterprise']], dtype=object)

In [76]:
encoder.feature_names_in_

array(['company_size'], dtype=object)

In [77]:
encoder.get_feature_names_out()

array(['company_size'], dtype=object)

In [79]:

enc = LabelEncoder()
enc.fit_transform(X_train['company_size'])

array([4, 3, 4, ..., 1, 2, 3], shape=(175000,))