In [1]:
import pandas as pd

In [2]:
# series, DataFrame

In [8]:
s = pd.Series([1,2,3,4], name='S1', index=['A', 'B', 'C', 'D'])

In [10]:
s.dtype

dtype('int64')

In [12]:
s.name = 's2'

In [13]:
s

A    1
B    2
C    3
D    4
Name: s2, dtype: int64

In [17]:
s.index = pd.RangeIndex(4)

In [18]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [19]:
s

0    1
1    2
2    3
3    4
Name: s2, dtype: int64

In [22]:
s == s

0    True
1    True
2    True
3    True
Name: s2, dtype: bool

In [23]:
# list[dict]
data = [
{"name": 'ram', 'age': 30, 'sal': '50000'},
{"name": 'shyam', 'age': 25, 'sal': '70000'},
{"name": 'ravi', 'age': 28, 'sal': '40000'}]

In [24]:
data

[{'name': 'ram', 'age': 30, 'sal': '50000'},
 {'name': 'shyam', 'age': 25, 'sal': '70000'},
 {'name': 'ravi', 'age': 28, 'sal': '40000'}]

In [28]:
df = pd.DataFrame(data, index=pd.RangeIndex(1001, 1004, name='index'))

In [29]:
df

        name  age    sal
index
1001     ram   30  50000
1002   shyam   25  70000
1003    ravi   28  40000

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 1001 to 1003
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     3 non-null      int64
 2   sal     3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [38]:
df['sal'] = df['sal'].astype('int')

In [42]:
df.reset_index(drop=False)

   index   name  age    sal
0   1001    ram   30  50000
1   1002  shyam   25  70000
2   1003   ravi   28  40000

In [52]:
df.loc[df['name']=='ram']

      name  age    sal
index
1001   ram   30  50000

In [60]:
df.iloc[df['sal']==50000, 2]

index
1001    50000
Name: sal, dtype: int64

In [62]:
# np.nan 
# pd.NA 
import numpy as np

In [85]:
df['exp'] = [4, 3, "unk"]

In [70]:
df

        name  age    sal  exp
index
1001     ram   30  50000    4
1002   shyam   25  70000    3
1003    ravi   28  40000  unk

In [71]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 1001 to 1003
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     3 non-null      int64
 2   sal     3 non-null      int64
 3   exp     3 non-null      object
dtypes: int64(2), object(1), str(1)
memory usage: 228.0+ bytes

In [86]:
# df['exp'].replace('unk', 0, inplace=True)
df.loc[1003, 'exp'] = np.nan

In [79]:
df

        name  age    sal exp
index
1001     ram   30  50000   4
1002   shyam   25  70000   3
1003    ravi   28  40000   0

In [80]:
df['exp'] = df['exp'].astype(pd.Int16Dtype())

In [82]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 1001 to 1003
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     3 non-null      int64
 2   sal     3 non-null      int64
 3   exp     3 non-null      Int16
dtypes: Int16(1), int64(2), str(1)
memory usage: 213.0 bytes

In [83]:
df.fillna(0)

        name  age    sal  exp
index
1001     ram   30  50000    4
1002   shyam   25  70000    3
1003    ravi   28  40000    0

In [87]:
df.dropna(subset=['exp'])

        name  age    sal exp
index
1001     ram   30  50000   4
1002   shyam   25  70000   3

In [88]:
# duplicates
df.duplicated()

index
1001    False
1002    False
1003    False
dtype: bool

In [89]:
df.drop_duplicates(keep='first')

        name  age    sal  exp
index
1001     ram   30  50000    4
1002   shyam   25  70000    3
1003    ravi   28  40000  NaN

In [100]:
data = pd.pivot_table(df, columns=df['name'], index='age', values='sal', aggfunc=['min', 'max']).T

In [101]:
data

age             25       28       30
    name
min ram        NaN      NaN  50000.0
    ravi       NaN  40000.0      NaN
    shyam  70000.0      NaN      NaN
max ram        NaN      NaN  50000.0
    ravi       NaN  40000.0      NaN
    shyam  70000.0      NaN      NaN

In [104]:
data.index

MultiIndex([('min',   'ram'),
            ('min',  'ravi'),
            ('min', 'shyam'),
            ('max',   'ram'),
            ('max',  'ravi'),
            ('max', 'shyam')],
           names=[None, 'name'])

In [107]:
data.loc[('min', 'ravi'), 28]

np.float64(40000.0)

In [106]:
data.columns

Index([25, 28, 30], dtype='int64', name='age')

In [113]:
df.groupby('name')['age'].agg(['mean', 'max'])

       mean  max
name
ram    30.0   30
ravi   28.0   28
shyam  25.0   25