In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../../data/titanic/train.csv")

In [4]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
data = pd.DataFrame({"C1":["A",'A', 'A', 'B', 'B', 'B'],
                    "C2": ['a', 'b', 'c', 'a', 'b', 'c'],
                    "C3": [1,2,3,4,5,6]})

In [6]:
data

  C1 C2  C3
0  A  a   1
1  A  b   2
2  A  c   3
3  B  a   4
4  B  b   5
5  B  c   6

In [11]:
data.pivot(columns='C2', values='C3', index='C1') # long to wide

C2  a  b  c
C1
A   1  2  3
B   4  5  6

In [82]:
pivot_tab = df.pivot_table(columns=['Pclass', "Sex"], index=['Survived', 'Embarked'], values=['Fare'], aggfunc=['mean', 'median'], fill_value=0, margins=True).T

In [108]:
pivot_tab

Survived                           0                                  1  \
Embarked                           C          Q           S           C
            Pclass Sex
mean   Fare 1      female  28.712500   0.000000  151.550000  117.710019
                   male    80.847160  90.000000   53.563316  112.197806
            2      female   0.000000   0.000000   18.250000   25.268457
                   male    25.418225  12.350000   18.997561   25.433350
            3      female  14.653125  10.904633   21.969018   14.717220
                   male     8.720842  11.841550   12.758689   11.435840
            All            35.443335  13.335904   20.743987   79.720926
median Fare 1      female  28.712500   0.000000  151.550000   83.158300
                   male    61.379200  90.000000   35.500000   63.358300
            2      female   0.000000   0.000000   17.000000   24.000000
                   male    25.860400  12.350000   13.000000   25.433350
            3      female  14.456250   7.750000   18.000000   15.245800
                   male     7.229200   7.750000    8.050000    9.879200
            All            14.458300   7.750000   10.500000   56.929200

Survived                                                All
Embarked                           Q          S
            Pclass Sex
mean   Fare 1      female  90.000000  96.743298  106.693750
                   male     0.000000  51.832739   67.226127
            2      female  12.350000  22.272951   21.970121
                   male     0.000000  20.516667   19.741782
            3      female  10.084033  13.171842   16.118810
                   male    12.916667  17.033450   12.661633
            All            13.182227  39.547081   32.096681
median Fare 1      female  90.000000  79.250000   83.158300
                   male     0.000000  30.500000   41.262500
            2      female  12.350000  23.000000   22.000000
                   male     0.000000  18.750000   13.000000
            3      female   7.768750  11.133300   12.475000
                   male     7.750000   8.050000    7.925000
            All             7.808350  26.000000   14.454200

In [26]:
test = pd.read_csv('../../data/titanic/test.csv')
result = pd.read_csv('../../data/titanic/gender_submission.csv')

In [27]:
test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [28]:
result

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [38]:
data = pd.concat((test, result), axis=1)

In [41]:
data = data.iloc[:, 1:].copy()

In [42]:
data

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,PassengerId,Survived
0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,892,0
1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,893,1
2,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,894,0
3,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,895,0
4,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,896,1
...,...,...,...,...,...,...,...,...,...,...,...,...
413,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,1305,0
414,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,1306,1
415,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,1307,0
416,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,1308,0
417,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,1309,0

In [43]:
data

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,PassengerId,Survived
0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,892,0
1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,893,1
2,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,894,0
3,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,895,0
4,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,896,1
...,...,...,...,...,...,...,...,...,...,...,...,...
413,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,1305,0
414,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,1306,1
415,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,1307,0
416,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,1308,0
417,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,1309,0

In [109]:
df.join()

TypeError: DataFrame.join() missing 1 required positional argument: 'other'

In [65]:
d1 = pd.DataFrame(
    {"Id": [1,2,3,4,5,6],
    "Name":["A", 'B', 'C', 'D', 'E', 'F']}
)

d2 = pd.DataFrame({"Id": [1,2,3,4,5,6,7],
                  "Dept": ['HR', 'Sales', 'Tech', "IT", 'Sales', 'Design', "IT"]})

In [66]:
d1

   Id Name
0   1    A
1   2    B
2   3    C
3   4    D
4   5    E
5   6    F

In [67]:
d2

   Id    Dept
0   1      HR
1   2   Sales
2   3    Tech
3   4      IT
4   5   Sales
5   6  Design
6   7      IT

In [110]:
d2.join(d1, lsuffix="__d1", how='left')

   Id__d1    Dept   Id Name
0       1      HR  1.0    A
1       2   Sales  2.0    B
2       3    Tech  3.0    C
3       4      IT  4.0    D
4       5   Sales  5.0    E
5       6  Design  6.0    F
6       7      IT  NaN  NaN

In [112]:
pd.merge(d1, d2, on='Id', how='right_anti')

   Id Name Dept
6   7  NaN   IT

In [83]:
pivot_tab

Survived                           0                                  1  \
Embarked                           C          Q           S           C
            Pclass Sex
mean   Fare 1      female  28.712500   0.000000  151.550000  117.710019
                   male    80.847160  90.000000   53.563316  112.197806
            2      female   0.000000   0.000000   18.250000   25.268457
                   male    25.418225  12.350000   18.997561   25.433350
            3      female  14.653125  10.904633   21.969018   14.717220
                   male     8.720842  11.841550   12.758689   11.435840
            All            35.443335  13.335904   20.743987   79.720926
median Fare 1      female  28.712500   0.000000  151.550000   83.158300
                   male    61.379200  90.000000   35.500000   63.358300
            2      female   0.000000   0.000000   17.000000   24.000000
                   male    25.860400  12.350000   13.000000   25.433350
            3      female  14.456250   7.750000   18.000000   15.245800
                   male     7.229200   7.750000    8.050000    9.879200
            All            14.458300   7.750000   10.500000   56.929200

Survived                                                All
Embarked                           Q          S
            Pclass Sex
mean   Fare 1      female  90.000000  96.743298  106.693750
                   male     0.000000  51.832739   67.226127
            2      female  12.350000  22.272951   21.970121
                   male     0.000000  20.516667   19.741782
            3      female  10.084033  13.171842   16.118810
                   male    12.916667  17.033450   12.661633
            All            13.182227  39.547081   32.096681
median Fare 1      female  90.000000  79.250000   83.158300
                   male     0.000000  30.500000   41.262500
            2      female  12.350000  23.000000   22.000000
                   male     0.000000  18.750000   13.000000
            3      female   7.768750  11.133300   12.475000
                   male     7.750000   8.050000    7.925000
            All             7.808350  26.000000   14.454200

In [85]:
pd.melt(pivot_tab) # wide-to-long

   Survived Embarked      value
0         0        C  28.712500
1         0        C  80.847160
2         0        C   0.000000
3         0        C  25.418225
4         0        C  14.653125
..      ...      ...        ...
93      All           22.000000
94      All           13.000000
95      All           12.475000
96      All            7.925000
97      All           14.454200

[98 rows x 3 columns]

In [92]:
data = df.set_index('Pclass').stack()

In [103]:
data.loc[3].loc["PassengerId"]

PassengerId      1
PassengerId      3
PassengerId      5
PassengerId      6
PassengerId      8
              ...
PassengerId    883
PassengerId    885
PassengerId    886
PassengerId    889
PassengerId    891
Length: 491, dtype: object

In [105]:
df.to_csv('../../data/file.csv', index=False)

{(3, 'PassengerId'): 891,
 (3, 'Survived'): 0,
 (3, 'Name'): 'Dooley, Mr. Patrick',
 (3, 'Sex'): 'male',
 (3, 'Age'): 32.0,
 (3, 'SibSp'): 0,
 (3, 'Parch'): 0,
 (3, 'Ticket'): '370376',
 (3, 'Fare'): 7.75,
 (3, 'Cabin'): nan,
 (3, 'Embarked'): 'Q',
 (1, 'PassengerId'): 890,
 (1, 'Survived'): 1,
 (1, 'Name'): 'Behr, Mr. Karl Howell',
 (1, 'Sex'): 'male',
 (1, 'Age'): 26.0,
 (1, 'SibSp'): 0,
 (1, 'Parch'): 0,
 (1, 'Ticket'): '111369',
 (1, 'Fare'): 30.0,
 (1, 'Cabin'): 'C148',
 (1, 'Embarked'): 'C',
 (2, 'PassengerId'): 887,
 (2, 'Survived'): 0,
 (2, 'Name'): 'Montvila, Rev. Juozas',
 (2, 'Sex'): 'male',
 (2, 'Age'): 27.0,
 (2, 'SibSp'): 0,
 (2, 'Parch'): 0,
 (2, 'Ticket'): '211536',
 (2, 'Fare'): 13.0,
 (2, 'Cabin'): nan,
 (2, 'Embarked'): 'S'}